<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\AliasesLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;

class AliasesLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@472
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use AliasesLoader {
                getAliasesFromContainersLoaders as public;
            }
        };
    }

    public function testGetAliasesFromContainersLoadersMethod(): void
    {
        $this->assertIsArray($this->trait->getAliasesFromContainersLoaders());
    }
}
