<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\CommandsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class CommandsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@404
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use CommandsLoader {
                getCommandsFromContainers as public;
                getCommandsFromShip as public;
            }
        };
    }

    public function testGetCommandsFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getCommandsFromContainers());
    }

    public function testGetCommandsFromShipMethod(): void
    {
        $this->assertIsString($this->trait->getCommandsFromShip());
    }
}
