<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\CommandsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class CommandsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@404
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use CommandsLoader {
                getCommandsFromContainers as public;
                getCommandsFromShip as public;
            }
        };
    }

    public function testGetCommandsFromContainersMethod()
    {
        $isArray = is_array($this->trait->getCommandsFromContainers());
        $this->assertTrue($isArray);
    }

    public function testGetCommandsFromShipMethod()
    {
        $isString = is_string($this->trait->getCommandsFromShip());
        $this->assertTrue($isString);
    }
}
