<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\ConfigsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class ConfigsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@402
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use ConfigsLoader {
                getConfigsFromContainers as public;
                getConfigsFromShip as public;
                getConfigsFromPackage as public;
            }
        };
    }

    public function testGetAliasesFromContainersLoadersMethod()
    {
        $isArray = is_array($this->trait->getConfigsFromContainers());
        $this->assertTrue($isArray);
    }

    public function testGetConfigsFromShipMethod()
    {
        $isArray = is_array($this->trait->getConfigsFromShip());
        $this->assertTrue($isArray);
    }

    public function testConfigsFromPackageMethod()
    {
        $isArray = is_array($this->trait->getConfigsFromPackage());
        $this->assertTrue($isArray);
    }
}
