<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\HelpersLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class HelpersLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@402
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use HelpersLoader {
                getHelpersFromShip as public;
                getHelpersFromContainers as public;
            }
        };
    }

    public function testGetHelpersFromShipMethod()
    {
        $isArray = is_array($this->trait->getHelpersFromShip());
        $this->assertTrue($isArray);
    }

    public function testGetHelpersFromContainersMethod()
    {
        $isArray = is_array($this->trait->getHelpersFromContainers());
        $this->assertTrue($isArray);
    }
}
