<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\MiddlewareLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;

class MiddlewareLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@408
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use MiddlewareLoader {
                getMiddlewareClassesLoadersFromContainers as public;
                getMiddlewareFromClassesLoaders as public;
            }
        };
    }

    public function testGetMiddlewareClassesLoadersFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getMiddlewareClassesLoadersFromContainers());
    }

    public function testGetMiddlewareFromClassesLoadersMethod(): void
    {
        $this->assertIsArray($this->trait->getMiddlewareFromClassesLoaders());
    }
}
