<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\MiddlewareLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class MiddlewareLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@408
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use MiddlewareLoader {
                getMiddlewareClassesLoadersFromContainers as public;
                getMiddlewareFromClassesLoaders as public;
            }
        };
    }

    public function testGetMiddlewareClassesLoadersFromContainersMethod()
    {
        $isArray = is_array($this->trait->getMiddlewareClassesLoadersFromContainers());
        $this->assertTrue($isArray);
    }

    public function testGetMiddlewareFromClassesLoadersMethod()
    {
        $isArray = is_array($this->trait->getMiddlewareFromClassesLoaders());
        $this->assertTrue($isArray);
    }
}
