<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\MigrationsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class MigrationsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@408
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use MigrationsLoader {
                getMigrationsFromShip as public;
                getMigrationsFromContainers as public;
            }
        };
    }

    public function testGetMigrationsFromShipMethod()
    {
        $isString = is_string($this->trait->getMigrationsFromShip());
        $this->assertTrue($isString);
    }

    public function testGetMigrationsFromContainersMethod()
    {
        $isArray = is_array($this->trait->getMigrationsFromContainers());
        $this->assertTrue($isArray);
    }
}
