<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\ProvidersLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class ProvidersLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@406
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use ProvidersLoader {
                getProvidersFromShip as public;
                getProvidersFromContainers as public;
                getProvidersFromContainersLoaders as public;
            }
        };
    }

    public function testGetProvidersFromShipMethod(): void
    {
        $this->assertIsArray($this->trait->getProvidersFromShip());
    }

    public function testGetProvidersFromContainers(): void
    {
        $this->assertIsArray($this->trait->getProvidersFromContainers());
    }

    public function testGetProvidersFromContainersLoaders(): void
    {
        $this->assertIsArray($this->trait->getProvidersFromContainersLoaders());
    }
}
