<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\RoutesLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class RoutesLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@400
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use RoutesLoader {
                getApiRoutesFromContainers as public;
                getWebRoutesFromContainers as public;
                getCliRoutesFromContainers as public;
            }
        };
    }

    public function testGetApiRoutesFromContainersMethod()
    {
        $isArray = is_array($this->trait->getApiRoutesFromContainers());
        $this->assertTrue($isArray);
    }

    public function testGetWebRoutesFromContainersMethod()
    {
        $isArray = is_array($this->trait->getWebRoutesFromContainers());
        $this->assertTrue($isArray);
    }

    public function testGetCliRoutesFromContainersMethod()
    {
        $isArray = is_array($this->trait->getCliRoutesFromContainers());
        $this->assertTrue($isArray);
    }
}
