<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\RoutesLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class RoutesLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@400
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use RoutesLoader {
                getApiRoutesFromContainers as public;
                getWebRoutesFromContainers as public;
                getCliRoutesFromContainers as public;
            }
        };
    }

    public function testGetApiRoutesFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getApiRoutesFromContainers());
    }

    public function testGetWebRoutesFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getWebRoutesFromContainers());
    }

    public function testGetCliRoutesFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getCliRoutesFromContainers());
    }
}
