<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\SeedersLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;

class SeedersLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@402
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use SeedersLoader {
                getSeedersFromContainers as public;
                getSeedersFromShip as public;
            }
        };
    }

    public function testGetSeedersFromContainersMethod()
    {
        $isArray = is_array($this->trait->getSeedersFromContainers());
        $this->assertTrue($isArray);
    }

    public function testSeedersFromShipMethod()
    {
        $isArray = is_array($this->trait->getSeedersFromShip());
        $this->assertTrue($isArray);
    }
}
