<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\TranslationsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class TranslationsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@412
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use TranslationsLoader {
                getTranslationsFromShip as public;
                getTranslationsFromContainers as public;
            }
        };
    }

    public function testGetTranslationsFromShipMethod()
    {
        $this->assertTrue(is_string($this->trait->getTranslationsFromShip()) || is_null($this->trait->getTranslationsFromShip()));
    }

    public function testTranslationsFromContainersMethod()
    {
        $isArray = is_array($this->trait->getTranslationsFromContainers());
        $this->assertTrue($isArray);
    }
}
