<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\TranslationsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;

class TranslationsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@412
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use TranslationsLoader {
                getTranslationsFromShip as public;
                getTranslationsFromContainers as public;
            }
        };
    }

    public function testGetTranslationsFromShipMethod(): void
    {
        $this->assertTrue(is_string($this->trait->getTranslationsFromShip()) || is_null($this->trait->getTranslationsFromShip()));
    }

    public function testTranslationsFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getTranslationsFromContainers());
    }
}
