<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\ViewsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;

class ViewsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@398
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use ViewsLoader {
                getViewsFromContainers as public;
            }
        };
    }

    public function testGetViewsFromContainersMethod(): void
    {
        $this->assertIsArray($this->trait->getViewsFromContainers());
    }
}
