<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Loaders;

use AlxDorosenco\PortoForLaravel\Loaders\ViewsLoader;
use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FilesAndDirectories;

class ViewsLoaderTraitTest extends TestCase
{
    /**
     * @var __anonymous@398
     */
    private $trait;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FilesAndDirectories;
            use ViewsLoader {
                getViewsFromContainers as public;
            }
        };
    }

    public function testGetViewsFromContainersMethod()
    {
        $isArray = is_array($this->trait->getViewsFromContainers());
        $this->assertTrue($isArray);
    }
}
