<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Traits;

use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\Console;

class ConsoleTraitTest extends TestCase
{
    /**
     * @var __anonymous@388
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use Console {
                getPath as public;
                getNamespaceRequest as public;
                getNamespaceResponse as public;
                getNamespaceRedirectResponse as public;
                rootNamespace as public;
                getContainersNamespace as public;
                getShipNamespace as public;
            }
        };
    }

    /***
     * @return void
     */
    public function testGetPathMethod(): void
    {
        $this->assertIsString($this->trait->getPath('test'));
    }

    /**
     * @return void
     */
    public function testGetNamespaceRequestMethod(): void
    {
        $this->assertIsString($this->trait->getNamespaceRequest());
    }

    /**
     * @return void
     */
    public function testGetNamespaceResponseMethod(): void
    {
        $this->assertIsString($this->trait->getNamespaceResponse());
    }

    /**
     * @return void
     */
    public function testGetNamespaceRedirectResponseMethod(): void
    {
        $this->assertIsString($this->trait->getNamespaceRedirectResponse());
    }

    /***
     * @return void
     */
    public function testRootNamespaceMethod(): void
    {
        $this->assertIsString($this->trait->rootNamespace());
    }

    /***
     * @return void
     */
    public function testGetContainersNamespaceMethod(): void
    {
        $this->assertIsString($this->trait->getContainersNamespace());
    }

    /***
     * @return void
     */
    public function testGetShipNamespaceMethod(): void
    {
        $this->assertIsString($this->trait->getShipNamespace());
    }
}
