<?php

namespace AlxDorosenco\PortoForLaravel\Tests\Unit\Traits;

use AlxDorosenco\PortoForLaravel\Tests\TestCase;
use AlxDorosenco\PortoForLaravel\Traits\FactoryExtension;

class FactoryExtensionTraitTest extends TestCase
{
    /**
     * @var __anonymous@394
     */
    private $trait;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->trait = new class {
            use FactoryExtension {
                newFactory as public;
            }
        };
    }

    /**
     * @return void
     */
    public function testNewFactoryMethod(): void
    {
        $this->assertNull($this->trait->newFactory());
    }
}
